### ISSUE TITLE
Icon Tooltip works fine, but widget popup is empty

### ISSUE THREAD

**Issue by jpmgsxr** [jsalatas/plasma-pstate#44]
Same issue from: https://github.com/jsalatas/plasma-pstate/issues/13

Difference is, only file in /etc/sudoers.d is 99-plasma-pstate.

If I "configure" and uncheck/recheck "use sudo for reading values" everything shows up but I cannot make changes.

Distribution is openSUSE Tumbleweed

**Comment by jsalatas** [comment]
Didi you try the solution there? It should work as AFAIK opensuse also uses the wheel group instead of sudo

**Comment by jpmgsxr** [comment]
I don't have wheel in there, just the 99-plasma-pstate for sudoers.d so his solution didn't work for me.

**Comment by jsalatas** [comment]
What will happen if you run the following? 
`sudo /usr/share/plasma/plasmoids/gr.ictpro.jsalatas.plasma.pstate/contents/code/set_prefs.sh -read-all`
does it ask you for a password?
what is the output?

**Comment by jpmgsxr** [comment]
`sudo /usr/share/plasma/plasmoids/gr.ictpro.jsalatas.plasma.pstate/contents/code/set_prefs.sh -read-all`

>{"cpu_min_perf":"11","cpu_max_perf":"100","cpu_turbo":"true","gpu_min_freq":"300","gpu_max_freq":"1100","gpu_min_limit":"300","gpu_max_limit":"1100","gpu_boost_freq":"1100","gpu_cur_freq":"467","cpu_governor":"powersave","energy_perf":"balance_performance"}

**Comment by jsalatas** [comment]
does it ask you for a password?

**Comment by jpmgsxr** [comment]
Yes

**Comment by jsalatas** [comment]
It shouldn't ask you. 

What is the output of 
```
sudo cat /etc/sudoers.d/99-plasma-pstate
```

**Comment by jpmgsxr** [comment]
sudo cat /etc/sudoers.d/99-plasma-pstate
[sudo] password for root: 
%wheel ALL=NOPASSWD: /usr/share/plasma/plasmoids/gr.ictpro.jsalatas.plasma.pstate/contents/code/set_prefs.sh

**Comment by jpmgsxr** [comment]
https://github.com/jsalatas/plasma-pstate/issues/4 

Looking into this

**Comment by jsalatas** [comment]
Doesn't make sense :\

Can you please restart your PC? :\

**Comment by jpmgsxr** [comment]
Fixed. openSUSE doesn't add the user to the wheel group by default since it uses su. Added user to wheel and it is working fine. Sorry for the runaround.

**Comment by GAlexMES** [comment]
@jsalatas I have the same issue with Ubuntu 19.10. Too answer your questions:

1. Does calling the script with sudo ask for a passwort: yes
2. What is the output of the script: The same as for jpmgsxr
3. Content of /etc/sudoers.d/99-plasma-pstate: The same as for jpmgsxr
4. Did I reboot: yes multiple times.

'groups wheel' returns 'wheel : wheel sudo'

Any ideas?

**Comment by jsalatas** [comment]
> Content of /etc/sudoers.d/99-plasma-pstate: The same as for jpmgsxr

lol! That's an interesting one. I guess the installation script is confused with your username (wheel) as in some distros there is a wheel group instead of a sudo group. I guess I need to review it (maybe one can have a username called sudo). Anyway..... could you please modify the  /etc/sudoers.d/99-plasma-pstate and instead of 

```
%wheel` ALL=NOPASSWD: /usr/share/plasma/plasmoids/gr.ictpro.jsalatas.plasma.pstate/contents
```
make it 
```
%sudo` ALL=NOPASSWD: /usr/share/plasma/plasmoids/gr.ictpro.jsalatas.plasma.pstate/contents
```
then reboot and see if that fixed your issue? It guess you will be ok.

**Comment by GAlexMES** [comment]
Content is now:
`%sudo ALL=NOPASSWD: /usr/share/plasma/plasmoids/gr.ictpro.jsalatas.plasma.pstate/contents/code/set_prefs.sh`

I rebooted. But still have an empty dialog.
Calling the script with sudo still needs a passwort.
Executing `id` gives me `... 27(sudo) ... `

**Comment by jsalatas** [comment]
I honestly have no idea :\

Clearly the issue is that it still asks you for password when you run it, so you need to figure it out. I would recommend to uninstall the widget and then try installing again after you have removed the wheel user or something :\

Sorry that I'm unable to help you :(

**Comment by GAlexMES** [comment]
I reinstalled and rebooted and still can't call it without a password.

> %sudo ALL=NOPASSWD: /usr/share/plasma/plasmoids/gr.ictpro.jsalatas.plasma.pstate/contents/code/set_prefs.sh

**Comment by adojck** [comment]
> I reinstalled and rebooted and still can't call it without a password.
> 
> > %sudo ALL=NOPASSWD: /usr/share/plasma/plasmoids/gr.ictpro.jsalatas.plasma.pstate/contents/code/set_prefs.sh

Are you in `sudo` group? You can use `gpasswd -a <user> sudo` to add yourself to this group. Otherwise change `sudo` to `wheel` in `/etc/sudoers.d/99-plasma-pstate`

And note that your `/etc/sudoers.d/99-plasma-pstate` is not same like **jpmgsxr** has

**Comment by DerAlSem** [comment]
I'd suggest to add a note to README.md for OpenSUSE users (or may be all users) to check, that they are in WHEEL group. As soon, as i've added my user to wheel group the popup started to show all it supposed to show.
